# Generated by Django 2.0.7 on 2020-07-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='HouseForm',
        ),
    ]
