# Generated by Django 2.0.7 on 2020-07-18 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20200717_2325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseForm',
            new_name='House',
        ),
    ]
