# Generated by Django 2.0.7 on 2020-07-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20200717_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='fireplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='electric',
            field=models.BooleanField(default=False),
        ),
    ]
